name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Curriculum.tex
          latexmk_use_xelatex: true

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Curriculum-PDF
          path: Curriculum.pdf
